server:
  port: 8082

spring:
  application:
    name: inventory-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 5
          max-interval: 5s
          multiplier: 1.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/